非同期通信前の修正
asahi0229/chat-space pull request #6
Opened 2019-02-12 06:14 UTC by asahi0229

2019-02-12 06:17 UTC, asahi0229 commented
# What
chatspaceのエラー全部を解決して、同期通信のchatspaceが完成した
# Why
chatspaceを使えるようにするため

2019-02-12 06:20 UTC, asahi0229 commented
# What
chatspaceのエラー全部を解決して、同期通信のchatspaceが完成した
# Why
chatspaceを使うようにするため

2019-02-12 06:24 UTC, TOMARUMARU commented on app/assets/stylesheets/mixins/vendor_prefix.scss
> +// $prefixes: -webkit-, -moz-, -ms-, -o-, '';
こちらのファイル必要ですか？全てコメントアウトされているようです

2019-02-12 06:24 UTC, TOMARUMARU commented on app/controllers/groups_controller.rb
> +  end
end と def の間改行いれましょう

2019-02-12 06:39 UTC, asahi0229 commented on app/assets/stylesheets/mixins/vendor_prefix.scss
> +// $prefixes: -webkit-, -moz-, -ms-, -o-, '';
deleteしました

2019-02-12 06:40 UTC, asahi0229 commented on app/controllers/groups_controller.rb
> +  end
修正しました

2019-02-12 06:42 UTC, yusukeyamane commented
変更がPushされていないようです。

2019-02-12 07:58 UTC, asahi0229 commented
# What
帰ってきたjsonをdoneメソッドで受け取り、HTMLに変換するまでのコードを書いた
# Why
非同期通信でメッセージを送るため

2019-02-12 08:03 UTC, ghost requested changes

2019-02-12 08:03 UTC, hiroki5123 commented on app/uploaders/image_uploader.rb
> + process resize_to_fit: [800, 800]
インデントがずれています

2019-02-12 08:03 UTC, hiroki5123 commented on app/assets/javascripts/messages.js
> +                  .upper-message
ここってhamlの書き方できないような気がするのですが、これで正常にメッセージはappendされていますか？

2019-02-12 08:03 UTC, hiroki5123 commented
非同期で送っているGIFをこちらに添付してください。
よろしくお願い致します。

2019-02-12 08:09 UTC, asahi0229 commented on app/assets/javascripts/messages.js
> +                  .upper-message
HTMLじゃないといけないってことですか？

一つ教えてほしんですけど、jsonからの返信ってどうやって知ることができるんですか？

2019-02-12 08:12 UTC, asahi0229 commented on app/uploaders/image_uploader.rb
> + process resize_to_fit: [800, 800]
修正しました

2019-02-12 08:15 UTC, hiroki5123 commented on app/assets/javascripts/messages.js
> +                  .upper-message
> HTMLじゃないといけないってことですか？

その通りです。

> 一つ教えてほしんですけど、jsonからの返信ってどうやって知ることができるんですか？

こちらは現時点で @asahi0229 さんのコードの挙動を確認できないので、大変恐れ入りますがTECH::CONNECTにてご質問していただきますよう、お願い致します。

2019-02-14 03:41 UTC, asahi0229 commented
# What
message 非同期通信にした
# Why
いちいちリロードするのがめんどくさいから

2019-02-14 03:42 UTC, asahi0229 commented
下にgif貼っときます
https://i.gyazo.com/f6897b1b66a791db916c3c6d7df7049b.mp4

2019-02-14 04:01 UTC, miyagit commented on app/assets/javascripts/message.js
> +      $('.form__message').val('');
こちらform属性のresetメソッドを使いましょう。

2019-02-14 04:01 UTC, miyagit commented on app/assets/javascripts/message.js
> +      // $('.form__message').remove();
コメントアウトを削除しましょう。

2019-02-14 04:01 UTC, miyagit commented on app/views/shared/_side_bar.html.haml
>      - current_user.groups.each do |group|
部分テンプレートを使いましょう

2019-02-14 04:22 UTC, asahi0229 commented on app/assets/javascripts/message.js
> +      // $('.form__message').remove();
修正しました

2019-02-14 05:26 UTC, asahi0229 commented on app/assets/javascripts/message.js
> +      $('.form__message').val('');
修正しました

2019-02-14 05:36 UTC, asahi0229 commented on app/views/shared/_side_bar.html.haml
>      - current_user.groups.each do |group|
もう少し具体的に教えてもらえませんか？

2019-02-14 05:40 UTC, hirozak commented on app/views/shared/_side_bar.html.haml
>      - current_user.groups.each do |group|
renderメソッドを使います。カリキュラムに出てきているので分からなければメンターに聞きましょう

2019-02-14 06:27 UTC, merged